import type { Metadata } from 'next'
import { Geist, Geist_Mono, Familjen_Grotesk } from 'next/font/google'
import './globals.css'
import NavBar from '@/common/navbar/page'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

const grotesk = Familjen_Grotesk({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-familjen-grotesk',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${grotesk.variable} antialiased`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  )
}
